---
site_name: Unlogged Documentation
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: custom
  features:
    - content.code.copy
    - content.tabs.link
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true